name: Algs build and push

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment 
        required: true
        options: 
        - staging
        - beta
        - stable
        - eu-aws
        - tyuio
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: false
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: test echo
        run: echo 'lalala'
